# Generated by Django 4.2.6 on 2024-02-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
