# Generated by Django 4.2.6 on 2024-03-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_skill',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
