# Generated by Django 4.2.6 on 2024-03-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_user_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('drawing', 'drawing'), ('communication', 'communication'), ('crafting', 'crafting'), ('coding', 'coding')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
